# reBop probe configurations

# reBop User configuration
user:
  rebopapikey: ""

# reBop server
rebopserver:
  proto: "https"
  host: "api.rebop.io"
  port: "443"

# ACME Certificate Authority Configuration
acme:
  cadirurl: ""
  useremail: ""
  hostname: ""

# local cache database
probe:
  filedb: "./reBop-probe.db"
